### ISSUE TITLE
Action for issue deletion

### ISSUE THREAD

**Issue by Jakobus42** [Jakobus42/webserv#5]
Create a github action to automatically delete a issue which is tied to a pull request after merging the target branch.
This should be added under **.github/workflows/**.
Make sure to create a seperat file for this action.

**Comment by Ksj14-kumar** [comment]
Hi @Jakobus42 
Could you please assign me this issue?

**Comment by Ksj14-kumar** [comment]
Hi @Jakobus42 
I have raised a [PR](https://github.com/Jakobus42/webserv/pull/8) for this issue pls check

**Comment by Jakobus42** [comment]
Hi @Ksj14-kumar,

Thank you for your effort and the work you've done on this! 

I wanted to mention a couple of things regarding your pull request:

Branch Deletion: GitHub already provides a built-in feature to automatically delete branches after a pull request is merged. You can enable this feature under the repository settings.

The initial issue was rather about closing **issues** after a merge of a PR.
After some research, it looks like the issue you're addressing isn't actually an issue that needs solving with a custom action. GitHub already provides ways to automatically close issues when a pull request is merged by simply using certain keywords in the pull request description, such as closes #<issue-number>, fixes #<issue-number>, etc. When these keywords are included in the PR description, GitHub will automatically close the associated issue once the PR is merged.

Since GitHub handles both branch deletion and issue closing automatically, this specific workflow may not be necessary. However, I truly appreciate your initiative in trying to keep the repository clean and efficient!

Thanks again for your contribution!

Best regards,
Jakob
